version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=ddurieux-glpi-app
