name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Review plan before apply'
        required: false
        default: ''

jobs:
  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Import Terraform Plan
        uses: actions/download-artifact@v2
        with:
          name: tf.plan
          path: ./

      - name: Setup Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 'latest'
          terraform_wrapper: false

      - name: Prepare environment variables
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          # Parse Azure secret into Packer variables
          export ARM_CLIENT_ID = $(cat $AZURE_CREDENTIALS | jq -r '.clientId') 
          export ARM_CLIENT_SECRET = $(cat $AZURE_CREDENTIALS | jq -r '.clientSecret')
          export ARM_SUBSCRIPTION_ID = $(cat $AZURE_CREDENTIALS | jq -r '.subscriptionId')
          export ARM_TENANT_ID = $(cat $AZURE_CREDENTIALS | jq -r '.tenantId')

      - name: Terraform Apply
        id: apply
        run: terraform apply -input=false tf.plan
