name: Packer Build VHD

on:
  push:

env:
  PRODUCT_VERSION: "latest" # or: "latest"

jobs:
  packer_validate:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Prepare environment variables
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          # Parse Azure secret into Packer variables
          echo $(cat $AZURE_CREDENTIALS | jq -r '.clientId') >> $ARM_CLIENT_ID
          echo $(cat $AZURE_CREDENTIALS | jq -r '.clientSecret') >> $ARM_CLIENT_SECRET
          echo $(cat $AZURE_CREDENTIALS | jq -r '.subscriptionId') >> $ARM_SUBSCRIPTION_ID
          echo $(cat $AZURE_CREDENTIALS | jq -r '.tenantId') >> $ARM_TENANT_ID

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run packer init
        id: init
        run: "packer init packer.pkr.hcl"

      - name: Validate image with Packer
        run: |
          packer validate \
            -var "client_id=$ARM_CLIENT_ID \
            -var "client_secret=$ARM_CLIENT_SECRET \
            -var "tenant_id=$ARM_SUBSCRIPTION_ID \
            -var "subscription-id$ARM_TENANT_ID \
            packer.pkr.hcl

  packer_build:
    runs-on: ubuntu-latest
    name: Build
    needs: packer_validate
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Prepare environment variables
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          # Parse Azure secret into Packer variables
          export ARM_CLIENT_ID = $(cat $AZURE_CREDENTIALS | jq -r '.clientId') 
          export ARM_CLIENT_SECRET = $(cat $AZURE_CREDENTIALS | jq -r '.clientSecret')
          export ARM_SUBSCRIPTION_ID = $(cat $AZURE_CREDENTIALS | jq -r '.subscriptionId')
          export ARM_TENANT_ID = $(cat $AZURE_CREDENTIALS | jq -r '.tenantId')

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Setup `ansible`
        uses: ansible/setup-ansible@v2

      - name: Run `packer init`
        id: init
        run: "packer init ./maleo_infra_image/packer/packer.json"

      - name: Build image with Packer and Ansible
        run: |
          packer build \
            -var "client_id=$ARM_CLIENT_ID \
            -var "client_secret=$ARM_CLIENT_SECRET \
            -var "tenant_id=$ARM_SUBSCRIPTION_ID \
            -var "subscription-id$ARM_TENANT_ID \
            packer.pkr.hcl

      - name: Export VHD ID to text file
        run: |
          VHD_ID=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d ":" -f2)
          echo "${VHD_ID}"
