name: Packer Build VHD

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  PRODUCT_VERSION: "latest" # or: "latest"
  ARM_CLIENT_ID: "${{ secrets.ARM_CLIENT_ID }}"
  ARM_CLIENT_SECRET: "${{ secrets.ARM_CLIENT_SECRET }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.ARM_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.ARM_TENANT_ID }}"

jobs:
  packer_validate:
    runs-on: ubuntu-latest
    name: Packer Validate
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run packer init
        id: init
        run: "packer init packer.pkr.hcl"

      - name: Run packer validate
        run: |
          packer validate packer.pkr.hcl

  packer_build:
    runs-on: ubuntu-latest
    name: Packer Build
    needs: packer_validate
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init packer.pkr.hcl"

      - name: Build image with Packer and Ansible
        run: |
          packer build -force packer.pkr.hcl 

      - name: Export VHD ID to logs
        run: |
          VHD_ID=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d ":" -f2)
          echo "${VHD_ID}"
